name: Update
on: check_suite

jobs:
  send:
    name: Send new verison	
    runs-on: ubuntu-latest
    
    steps:
      - name: HTTP client
        run: echo RUN
        run: curl GET -X https://google.com
